name: Verible linter example
on:
  pull_request_target:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Verible action
        uses: chipsalliance/verible-linter-action@main
        with:
          extensions: |
            .sv
            .v
            .vh
            .svh
          extra_args: "--check_syntax=true"
          github_token: ${{ secrets.GITHUB_TOKEN }}